import React from 'react';
import { motion } from 'framer-motion';
import { 
  Target, BookOpen, TrendingUp, Award, Zap, Brain, 
  Sparkles, CheckCircle2, ArrowRight, Users, Clock, 
  BarChart3, Rocket, Star, ChevronRight
} from 'lucide-react';

const LandingPage = ({ onGetStarted }) => {
  const features = [
    {
      icon: Brain,
      title: "AI-Powered Roadmaps",
      description: "Get personalized learning paths generated by advanced AI, tailored to your goals and skill level."
    },
    {
      icon: Zap,
      title: "Adaptive Quizzes",
      description: "Smart quizzes that identify your weak areas and automatically adjust to help you improve faster."
    },
    {
      icon: TrendingUp,
      title: "Gamified Progress",
      description: "Earn XP, level up, and track your journey with an engaging gamification system that keeps you motivated."
    },
    {
      icon: BookOpen,
      title: "Multiple Learning Styles",
      description: "Choose between text summaries, video tutorials, or official documentation based on how you learn best."
    },
    {
      icon: Rocket,
      title: "Smart Caching",
      description: "Instantly access popular courses without waiting. Our system reuses optimized learning paths."
    },
    {
      icon: BarChart3,
      title: "Detailed Analytics",
      description: "Monitor your progress with comprehensive stats, see your weak areas, and celebrate your achievements."
    }
  ];

  const stats = [
    { number: "10K+", label: "Learning Paths" },
    { number: "50K+", label: "Quizzes Completed" },
    { number: "95%", label: "Success Rate" },
    { number: "24/7", label: "AI Availability" }
  ];

  const benefits = [
    "Learn any skill at your own pace",
    "Get instant feedback on your progress",
    "Save time with curated learning paths",
    "Never feel lost or overwhelmed",
    "Build confidence through achievement",
    "Join a community of learners"
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-indigo-50">
      
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-lg border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-xl flex items-center justify-center">
                <Target className="w-6 h-6 text-white" strokeWidth={2.5} />
              </div>
              <h1 className="text-2xl font-bold text-gray-900">Goal Stake</h1>
            </div>
            <button
              onClick={onGetStarted}
              className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold px-6 py-2.5 rounded-xl hover:shadow-lg hover:scale-[1.02] transition-all duration-200 flex items-center gap-2"
            >
              Get Started
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center"
          >
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
              className="inline-flex items-center gap-2 bg-indigo-50 text-indigo-600 px-4 py-2 rounded-full font-medium mb-6"
            >
              <Sparkles className="w-4 h-4" />
              AI-Powered Learning Platform
            </motion.div>

            <h1 className="text-6xl md:text-7xl font-bold text-gray-900 mb-6 leading-tight">
              Master Any Skill<br />
              <span className="bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                Your Way
              </span>
            </h1>

            <p className="text-xl text-gray-600 mb-10 max-w-2xl mx-auto leading-relaxed">
              Transform your learning journey with AI-powered roadmaps, adaptive quizzes, 
              and gamified progress tracking. Start achieving your goals today.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={onGetStarted}
                className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-bold px-8 py-4 rounded-xl shadow-lg hover:shadow-xl transition-all duration-200 flex items-center gap-2 text-lg"
              >
                Start Learning Free
                <Rocket className="w-5 h-5" />
              </motion.button>
              
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="bg-white text-gray-700 font-bold px-8 py-4 rounded-xl border-2 border-gray-200 hover:border-indigo-300 transition-all duration-200 flex items-center gap-2 text-lg"
              >
                Watch Demo
                <ChevronRight className="w-5 h-5" />
              </motion.button>
            </div>

            {/* Trust Indicators */}
            <div className="flex items-center justify-center gap-6 mt-12 text-sm text-gray-500">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-green-500" />
                No credit card required
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-green-500" />
                Free forever
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-green-500" />
                Cancel anytime
              </div>
            </div>
          </motion.div>

          {/* Hero Image/Illustration */}
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4, duration: 0.8 }}
            className="mt-16 relative"
          >
            <div className="bg-gradient-to-br from-indigo-100 to-purple-100 rounded-3xl p-8 shadow-2xl border border-indigo-200">
              <div className="bg-white rounded-2xl p-6 shadow-lg">
                {/* Mock Dashboard Preview */}
                <div className="grid grid-cols-3 gap-4 mb-6">
                  <div className="bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl p-4 text-white">
                    <p className="text-sm opacity-80">Level</p>
                    <p className="text-3xl font-bold">12</p>
                  </div>
                  <div className="bg-white rounded-xl p-4 border-2 border-gray-100">
                    <p className="text-sm text-gray-600">XP</p>
                    <p className="text-3xl font-bold text-gray-900">2,450</p>
                  </div>
                  <div className="bg-white rounded-xl p-4 border-2 border-gray-100">
                    <p className="text-sm text-gray-600">Courses</p>
                    <p className="text-3xl font-bold text-gray-900">8</p>
                  </div>
                </div>
                
                <div className="space-y-3">
                  {['Advanced Python', 'Machine Learning', 'Web Development'].map((course, idx) => (
                    <div key={idx} className="bg-gray-50 rounded-xl p-4 flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <BookOpen className="w-5 h-5 text-indigo-600" />
                        <span className="font-semibold text-gray-900">{course}</span>
                      </div>
                      <span className="text-sm text-indigo-600 font-medium">In Progress</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Decorative Elements */}
            <div className="absolute -top-6 -left-6 w-24 h-24 bg-yellow-400 rounded-full blur-3xl opacity-50"></div>
            <div className="absolute -bottom-6 -right-6 w-32 h-32 bg-purple-400 rounded-full blur-3xl opacity-50"></div>
          </motion.div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 px-6 bg-white border-y border-gray-200">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="text-center"
              >
                <p className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent mb-2">
                  {stat.number}
                </p>
                <p className="text-gray-600 font-medium">{stat.label}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              Everything You Need to Succeed
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Powerful features designed to accelerate your learning and help you achieve your goals faster.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  whileHover={{ y: -5 }}
                  className="bg-white rounded-2xl p-8 shadow-lg border border-gray-100 hover:shadow-xl transition-all duration-300"
                >
                  <div className="w-14 h-14 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl flex items-center justify-center mb-5">
                    <Icon className="w-7 h-7 text-white" />
                  </div>
                  <h3 className="text-xl font-bold text-gray-900 mb-3">{feature.title}</h3>
                  <p className="text-gray-600 leading-relaxed">{feature.description}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-20 px-6 bg-gradient-to-br from-indigo-50 to-purple-50">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              How It Works
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Start your learning journey in three simple steps
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              { step: "1", title: "Choose Your Goal", description: "Tell us what skill you want to master. From programming to design, we've got you covered.", icon: Target },
              { step: "2", title: "Get Your Roadmap", description: "Our AI generates a personalized learning path tailored to your current level and learning style.", icon: Brain },
              { step: "3", title: "Learn & Level Up", description: "Follow your roadmap, take quizzes, earn XP, and track your progress as you master new skills.", icon: Award }
            ].map((item, index) => {
              const Icon = item.icon;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.2 }}
                  className="relative"
                >
                  <div className="bg-white rounded-2xl p-8 shadow-lg border border-gray-100 text-center">
                    <div className="w-16 h-16 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-5 text-white text-2xl font-bold">
                      {item.step}
                    </div>
                    <Icon className="w-10 h-10 text-indigo-600 mx-auto mb-4" />
                    <h3 className="text-xl font-bold text-gray-900 mb-3">{item.title}</h3>
                    <p className="text-gray-600 leading-relaxed">{item.description}</p>
                  </div>
                  
                  {/* Connector Arrow */}
                  {index < 2 && (
                    <div className="hidden md:block absolute top-1/2 -right-4 transform -translate-y-1/2 z-10">
                      <ChevronRight className="w-8 h-8 text-indigo-300" />
                    </div>
                  )}
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
                Why Learners Choose Goal Stake
              </h2>
              <p className="text-xl text-gray-600 mb-8">
                Join thousands of learners who are achieving their goals faster with our innovative platform.
              </p>

              <div className="space-y-4">
                {benefits.map((benefit, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: index * 0.1 }}
                    className="flex items-center gap-3"
                  >
                    <div className="w-6 h-6 bg-green-500 rounded-full flex items-center justify-center flex-shrink-0">
                      <CheckCircle2 className="w-4 h-4 text-white" />
                    </div>
                    <span className="text-lg text-gray-700">{benefit}</span>
                  </motion.div>
                ))}
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="bg-gradient-to-br from-indigo-600 to-purple-600 rounded-3xl p-8 text-white shadow-2xl">
                <div className="mb-6">
                  <div className="flex items-center gap-2 mb-2">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <Star key={star} className="w-5 h-5 fill-yellow-400 text-yellow-400" />
                    ))}
                  </div>
                  <p className="text-lg italic mb-4">
                    "Goal Stake completely transformed how I learn. The AI-generated roadmaps are spot-on, 
                    and the gamification keeps me motivated every day!"
                  </p>
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center">
                      <Users className="w-6 h-6" />
                    </div>
                    <div>
                      <p className="font-bold">Sarah Johnson</p>
                      <p className="text-sm text-indigo-200">Full-Stack Developer</p>
                    </div>
                  </div>
                </div>

                <div className="border-t border-white/20 pt-6 grid grid-cols-2 gap-4 text-center">
                  <div>
                    <p className="text-3xl font-bold mb-1">18</p>
                    <p className="text-sm text-indigo-200">Skills Mastered</p>
                  </div>
                  <div>
                    <p className="text-3xl font-bold mb-1">94%</p>
                    <p className="text-sm text-indigo-200">Quiz Success Rate</p>
                  </div>
                </div>
              </div>

              {/* Decorative Elements */}
              <div className="absolute -top-6 -right-6 w-32 h-32 bg-indigo-300 rounded-full blur-3xl opacity-30"></div>
              <div className="absolute -bottom-6 -left-6 w-32 h-32 bg-purple-300 rounded-full blur-3xl opacity-30"></div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-6 bg-gradient-to-br from-indigo-900 via-purple-900 to-indigo-800 relative overflow-hidden">
        {/* Decorative Background */}
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-0 left-1/4 w-96 h-96 bg-white rounded-full blur-3xl"></div>
          <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-purple-300 rounded-full blur-3xl"></div>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-4xl mx-auto text-center relative z-10"
        >
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
            Ready to Transform Your Learning?
          </h2>
          <p className="text-xl text-indigo-100 mb-10">
            Join thousands of learners achieving their goals with Goal Stake. Start your journey today.
          </p>

          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={onGetStarted}
            className="bg-white text-indigo-600 font-bold px-10 py-5 rounded-xl shadow-2xl hover:shadow-3xl transition-all duration-200 flex items-center gap-3 mx-auto text-lg"
          >
            Get Started for Free
            <Rocket className="w-6 h-6" />
          </motion.button>

          <p className="text-indigo-200 mt-6">No credit card required • Free forever</p>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 py-12 px-6">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center gap-3 mb-4">
            <div className="w-10 h-10 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-xl flex items-center justify-center">
              <Target className="w-6 h-6 text-white" strokeWidth={2.5} />
            </div>
            <h3 className="text-2xl font-bold text-white">Goal Stake</h3>
          </div>
          <p className="mb-6">Master any skill, your way.</p>
          <p className="text-sm">© 2026 Goal Stake. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;